
name: social_media_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  async: ^2.11.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_cache_manager: ^3.3.2
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.1+2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.7.0
  giphy_picker: ^3.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.1
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_cropper: ^7.1.0
  image_editor_plus: ^1.0.6
  image_picker: ^1.1.2
  intl: any
  just_audio: ^0.9.39
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  photo_manager: ^3.2.0
  photo_manager_image_provider: ^2.1.1
  record: ^5.1.2
  rive: ^0.13.7
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  story_view: ^0.16.5
  swipe_to: ^1.0.6
  url_launcher: ^6.3.0
  uuid: ^4.4.0
  video_player: ^2.9.1
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/gifs/
    - assets/icons/
    - assets/svgs/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900 
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 23