name: social_media_app
description: "A new Flutter project."
publish_to: "none"

version: 1.4.0+7

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  cached_network_image: ^3.3.1 # Caching for network images to improve performance
  cloud_firestore: ^5.0.0 # Cloud Firestore for database services
  connectivity_plus: ^6.0.5 # Connectivity status (WiFi, mobile data)
  cupertino_icons: ^1.0.6 # iOS-style icons
  equatable: ^2.0.5 # Value equality for Dart objects
  firebase_auth: ^5.0.0 # Authentication services from Firebase
  firebase_core: ^3.0.0 # Core functionality for Firebase
  firebase_messaging: ^15.0.3 # Push notifications via Firebase
  firebase_storage: ^12.0.0 # Cloud storage for Firebase
  flutter:
    sdk: flutter # Flutter framework
  flutter_animate: ^4.5.0 # Animation library for Flutter
  flutter_bloc: ^8.1.5 # State management using the BLoC pattern
  flutter_cache_manager: ^3.3.2 # Manage cached files and data
  flutter_dotenv: ^5.1.0 # Load environment variables from a .env file
  flutter_image_compress: ^2.3.0 # Compress images before uploading
  flutter_local_notifications: ^17.2.1+2 # Local notifications for Flutter
  flutter_localizations:
    sdk: flutter # Localization support for Flutter
  flutter_screenutil: ^5.9.3 # Responsive design utilities
  flutter_speed_dial: ^7.0.0 # Floating action button with speed dial options
  flutter_staggered_grid_view: ^0.7.0 # Staggered grid view layout
  flutter_stripe: ^11.0.0 # Stripe payment integration for Flutter
  flutter_svg: ^2.0.10+1 # SVG image rendering
  fpdart: ^1.1.0 # Functional programming utilities for Dart
  geocoding: ^3.0.0 # Convert coordinates to human-readable addresses
  geolocator: ^12.0.0 # Get location information
  get_it: ^7.7.0 # Dependency injection for Flutter
  giphy_picker: ^3.0.2 # Pick GIFs from Giphy
  google_sign_in: ^6.2.1 # Google sign-in authentication
  googleapis: ^13.2.0 # Access Google APIs
  googleapis_auth: ^1.6.0 # Authentication for Google APIs
  http: ^1.2.2 # Simplified HTTP client for Dart
  image_cropper: ^7.1.0 # Crop images before use
  image_picker: ^1.1.2 # Select images from gallery or camera
  intl: any # Internationalization and localization utilities
  just_audio: ^0.9.39 # Audio playback capabilities
  loading_animation_widget: ^1.2.1 # Loading animations for better UX
  lottie: ^3.1.2 # Render animations created in Adobe After Effects
  path: ^1.9.0 # File path utilities
  path_provider: ^2.1.3 # Find commonly used locations on the filesystem
  permission_handler: ^11.3.1 # Request and check permissions
  photo_manager: ^3.2.0 # Manage photos and videos from the gallery
  photo_manager_image_provider: ^2.1.1 # Provide images from the photo manager
  record: ^5.1.2 # Record audio
  rive: ^0.13.7 # Rive animations for interactive designs
  share_plus: ^10.0.0 # Share content with other apps
  shared_preferences: ^2.2.3 # Store simple data persistently
  shimmer: ^3.0.0 # Shimmer effect for loading states
  smooth_page_indicator: ^1.1.0 # Page indicators for scrolling views
  story_view: ^0.16.5 # Create story-like views
  swipe_to: ^1.0.6 # Swipe-to-dismiss functionality
  url_launcher: ^6.3.0 # Launch URLs in the browser or apps
  uuid: ^4.4.0 # Generate universally unique identifiers
  video_player: ^2.9.1 # Video playback capabilities

dev_dependencies:
  flutter_lints: ^3.0.0 # Linting rules for Flutter projects
  flutter_test:
    sdk: flutter # Flutter testing framework

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/gifs/
    - assets/icons/
    - assets/svgs/
    - assets/lotties/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900 

# flutter_launcher_icons:
#   android: "launcher_icon"
#   image_path: "assets/images/app_logo.png"
#   min_sdk_android: 23
