name: social_media_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  animate_do: ^3.3.4
  async: ^2.11.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_image_compress: ^2.3.0
  flutter_screenutil: ^5.9.3
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  photo_manager: ^3.2.0
  photo_manager_image_provider: ^2.1.1
  photo_view: ^0.15.0
  rive: ^0.13.7
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  story_view: ^0.16.5
  stream_transform: ^2.1.0
  url_launcher: ^6.3.0
  uuid: ^4.4.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/gifs/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
