// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjdDYlhNFoWlaA3g7GPqJWQOztZVnJtik',
    appId: '1:803278246806:web:98b6fa1f6744239e2a03b7',
    messagingSenderId: '803278246806',
    projectId: 'socialmediaapp-58c5c',
    authDomain: 'socialmediaapp-58c5c.firebaseapp.com',
    databaseURL: 'https://socialmediaapp-58c5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaapp-58c5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMU_lqqWSVq-vdxAg3PXOi8F3BcpCm6g',
    appId: '1:803278246806:android:08bd4c18ab84f1992a03b7',
    messagingSenderId: '803278246806',
    projectId: 'socialmediaapp-58c5c',
    databaseURL: 'https://socialmediaapp-58c5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaapp-58c5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxisHWdqNf27d92OlXatR84rmwbZYJack',
    appId: '1:803278246806:ios:5b7d2dc6ff1e55c42a03b7',
    messagingSenderId: '803278246806',
    projectId: 'socialmediaapp-58c5c',
    databaseURL: 'https://socialmediaapp-58c5c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'socialmediaapp-58c5c.appspot.com',
    androidClientId: '803278246806-795bj6ocatq8g6ve245bq6btkvnqbnnq.apps.googleusercontent.com',
    iosClientId: '803278246806-l3kjc8dtp0j3ksdo6smi57no3jk41dqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

}