class MyAppRouteConst {
  MyAppRouteConst._();
  static const String splashRote = 'splashPage';
  static const String usenameRoute = 'userNamePage';
  static const String homeRoute = 'homePage';
  static const String loginRoute = 'loginPage';
  static const String signUpRoute = 'singupPage';
  static const String createPostRoute = 'createPostPage';
  static const String bottomNavRoute = 'bottomNavPage';
  static const String addProfilePage = 'addProfilePage';
  static const String interestSelectRoute = 'InterestSelctingPage';
  static const String locationPageRoute = 'locationPage';
  static const String profileLoadingRouter = 'profileLoadingPage';
  static const String mediaPickerRoute = 'mediaPickerPage';
  static const String otherUserProfile = 'otherUserprofile';
  static const String hashtagPostsRoute = 'hashtagPostsPage';
  static const String viewPostsDetailedRoute = 'viewPostDetailsPage';
  static const String createMultipleStatusRoute = 'createMultipleStatusPage';
  static const String personaChatRoute = 'personChatPage';
  static const String userVisitedListingRoute = 'userVisitedListingPage';
  static const String statusCreationRoute = 'statusCreationPage';
  static const String viewStatusRoute = 'viewStatusPage';
  static const String dobPageRoute = 'dobPageRoute';
  static const String notificationPage = 'notificationPage';
  static const String settingAndActivityPage = 'settingAndActivityPage';
  static const String accountSettingsPage = 'accountSettingsPage';
  static const String chatSettingPage = 'chatSettingPage';
  static const String notificationSettingsPage = 'notificationSettingsPage';
  static const String likedOrSavedPostsPage = 'likedOrSavedPostsPage';
  static const String aiChatPage = 'aiChatPage';
}
