// lib/core/constants/app_constants.dart

const List<String> interests = [
  'Music',
  'Books',
  'Movies',
  'TV Shows',
  'Art',
  'Dance',
  'Theater',
  'Museums',
  'Food',
  'Festivals',
//   'Fashion',
//   'Beauty',
//   'Travel',
//   'Photography',
//   'Health & Fitness',
//   'Home & Garden',
//   'Pets',
//   'DIY',
//   'Gadgets',
//   'Software',
//   'Programming',
//   'Gaming',
//   'Apps',
//   'AI',
//   'VR',
//   'Football',
//   'Basketball',
//   'Baseball',
//   'Cricket',
//   'Tennis',
//   'Running',
//   'Swimming',
//   'Yoga',
//   'Astronomy',
//   'Biology',
//   'Chemistry',
//   'Physics',
//   'Environmental Science',
//   'Medicine',
//   'Cooking',
//   'Gardening',
//   'Writing',
//   'Painting',
//   'Music Production',
//   'Board Games',
//   'Volunteering',
//   'Social Activism',
//   'Charity',
//   'Support Groups',
//   'Languages',
//   'History',
//   'Philosophy',
//   'Psychology',
//   'Science',
//   'Technology',
//   'Comedy',
//   'Celebrity Gossip',
//   'Reality TV',
//   'Podcasts',
//   'Animation'
];
